name: CI/CD Pipeline for Monitoring Stack

on:
  push:
    branches: [ "main" ]

jobs:
  # Công đoạn 1: CI (Kiểm tra lỗi)
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Compose Syntax Check
        run: docker compose config --quiet

  # Công đoạn 2: CD (Tự động Deploy - Chỉ chạy nếu công đoạn CI ở trên báo Xanh)
  cd-deploy:
    runs-on: ubuntu-latest
    needs: ci-test # Ép buộc phải qua được vòng gửi xe CI thì mới chạy vòng này
    
    steps:
      - name: Deploy to Ubuntu Server via SSH
        uses: appleboy/ssh-action@v1.0.3 # Một con Bot có sẵn trên GitHub chuyên đi SSH
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Các lệnh này sẽ chạy TRỰC TIẾP bên trong con Ubuntu của bạn:
            cd ~/prometheus-grafana # Di chuyển vào đúng thư mục chứa lab của bạn (sửa lại đường dẫn nếu bạn đặt thư mục tên khác)
            
            echo "Đang kéo code mới nhất từ GitHub về Server..."
            git pull origin main
            
            echo "Đang dọn dẹp và khởi động lại Docker..."
            docker compose down
            docker compose up -d
            
            echo "Hệ thống đã tự động deploy thành công hoàn toàn!"
